fix({{cookiecutter.provider}}/.github/workflows/pull-request.yml): corrected implementation of pull request workflow Fixes: #21

diff --git a/{{cookiecutter.provider}}/.github/workflows/pull-request.yml b/{{cookiecutter.provider}}/.github/workflows/pull-request.yml
--- a/{{cookiecutter.provider}}/.github/workflows/pull-request.yml
+++ b/{{cookiecutter.provider}}/.github/workflows/pull-request.yml
@@ -1,53 +1,43 @@
-{%raw%}
-name: release
+{% raw -%}
+name: build
 
 on:
-  push:
-    tags:
-      - v*.*.*
+  pull_request:
     paths-ignore:
       - docs
       - .devcontainer
       - examples
 
-env:
-  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-  # IF YOU NEED TO PUBLISH A NPM PACKAGE THEN ENSURE A NPM_TOKEN SECRET IS SET
-  # AND PUBLISH_NPM: TRUE. IF YOU WANT TO PUBLISH TO A PRIVATE NPM REGISTRY
-  # THEN ENSURE THE NPM_REGISTRY_URL IS CHANGED
-  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
-  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
-  PUBLISH_NPM: true
-  NPM_REGISTRY_URL: https://registry.npmjs.org
-  # IF YOU NEED TO PUBLISH A NUGET PACKAGE THEN ENSURE AN NUGET_PUBLISH_KEY
-  # SECRET IS SET AND PUBLISH_NUGET: TRUE. IF YOU WANT TO PUBLISH TO AN ALTERNATIVE
-  # NPM REGISTRY THEN ENSURE THE NPM_REGISTRY_URL IS CHANGED
-  NUGET_PUBLISH_KEY: ${{ secrets.NUGET_PUBLISH_KEY }}
-  NUGET_FEED_URL: https://api.nuget.org/v3/index.json
-  PUBLISH_NUGET: true
-  # IF YOU NEED TO PUBLISH A PYPI PACKAGE THEN ENSURE AN PYPI_API_TOKEN
-  # SECRET IS SET AND PUBLISH_PYPI: TRUE. IF YOU WANT TO PUBLISH TO AN ALTERNATIVE
-  # PYPI REGISTRY THEN ENSURE THE PYPI_REPOSITORY_URL IS SET. IF YOU ARE USING AN API_TOKEN THEN
-  # YOU DO NOT NEED TO CHANGE THE PYPI_USERNAME (__token__) , IF YOU ARE USING PASSWORD AUTHENTICATION THEN YOU WILL
-  # NEED TO CHANGE TO USE THE CORRECT PASSWORD
-  PYPI_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
-  PYPI_USERNAME: "__token__"
-  PYPI_REPOSITORY_URL: ""
-  PUBLISH_PYPI: true
-
 jobs:
-  publish_binary:
-    name: publish
+  build_sdk:
+    name: build_sdk
     runs-on: ubuntu-latest
-    permissions:
-      contents: write
+    strategy:
+      fail-fast: true
+      matrix:
+        dotnetversion:
+          - 6.0.x
+        goversion:
+          - {% endraw %}- {{ cookiecutter.__go_version_major }}.{{ cookiecutter.__go_version_minor }}.x{% raw %}
+        nodeversion:
+          - 16.x
+        pythonversion:
+          - "3.9"
+        javaversion:
+          - "11"
+        language:
+          - nodejs
+          - python
+          - dotnet
+          - go
+          # - java
+
     steps:
     - name: Checkout Repo
-      uses: actions/checkout@v3
+      uses: actions/checkout@v2
 
     - name: Unshallow clone for tags
       run: git fetch --prune --unshallow --tags
-
     - name: Install Go
       uses: actions/setup-go@v3
       with:
@@ -58,122 +48,45 @@ jobs:
       with:
         repo: pulumi/pulumictl
 
-    - name: Set PreRelease Version
-      run: echo "GORELEASER_CURRENT_TAG=v$(pulumictl get version --language generic)" >> $GITHUB_ENV
-    - name: Run GoReleaser
-      uses: goreleaser/goreleaser-action@v2
+    - name: Install pulumi
+      uses: pulumi/actions@v4
+
+    - if: ${{ matrix.language == 'nodejs'}}
+      name: Setup Node
+      uses: actions/setup-node@v2
       with:
-        args: -p 3 release --rm-dist
-        version: latest
+        node-version: ${{matrix.nodeversion}}
+        registry-url: https://registry.npmjs.org
 
-    strategy:
-      fail-fast: true
-      matrix:
-        goversion:
-        {%endraw%}- {{ cookiecutter.__go_version_major }}.{{ cookiecutter.__go_version_minor }}.x{%raw%}
+    - if: ${{ matrix.language == 'dotnet'}}
+      name: Setup DotNet
+      uses: actions/setup-dotnet@v1
+      with:
+        dotnet-version: ${{matrix.dotnetversion}}
 
-  publish_sdk:
-    name: Publish SDKs
-    runs-on: ubuntu-latest
-    needs: publish_binary
-    steps:
-      - name: Checkout Repo
-        uses: actions/checkout@v2
+    - if: ${{ matrix.language == 'python'}}
+      name: Setup Python
+      uses: actions/setup-python@v2
+      with:
+        python-version: ${{matrix.pythonversion}}
 
-      - name: Unshallow clone for tags
-        run: git fetch --prune --unshallow --tags
+    - if: ${{ matrix.language == 'java'}}
+      name: Setup Java
+      uses: actions/setup-java@v3
+      with:
+        cache: gradle
+        distribution: temurin
+        java-version: ${{matrix.javaversion}}
 
-      - name: Install Go
-        uses: actions/setup-go@v3
-        with:
-          go-version: ${{ matrix.goversion }}
+    - name: Build SDK
+      run: make build_${{ matrix.language }}
 
-      - name: Install pulumictl
-        uses: jaxxstorm/action-install-gh-release@v1.10.0
-        with:
-          repo: pulumi/pulumictl
-
-      - name: Install pulumi
-        uses: pulumi/actions@v4
-
-      - if: ${{ matrix.language == 'nodejs'}}
-        name: Setup Node
-        uses: actions/setup-node@v1
-        with:
-          node-version: ${{matrix.nodeversion}}
-          registry-url: ${{env.NPM_REGISTRY_URL}}
-
-      - if: ${{ matrix.language == 'dotnet'}}
-        name: Setup DotNet
-        uses: actions/setup-dotnet@v1
-        with:
-          dotnet-version: ${{matrix.dotnetversion}}
-
-      - if: ${{ matrix.language == 'java'}}
-        name: Setup Java
-        uses: actions/setup-java@v3
-        with:
-          cache: gradle
-          distribution: temurin
-          java-version: ${{matrix.javaversion}}
-
-      - if: ${{ matrix.language == 'python'}}
-        name: Setup Python
-        uses: actions/setup-python@v1
-        with:
-          python-version: ${{matrix.pythonversion}}
-
-      - name: Build SDK
-        run: make build_${{ matrix.language }}
-
-      - name: Check worktree clean
-        run: |
-          git update-index -q --refresh
-          if ! git diff-files --quiet; then
-              >&2 echo "error: working tree is not clean, aborting!"
-              git status
-              git diff
-              exit 1
-          fi
-
-      - if: ${{ matrix.language == 'python' && env.PUBLISH_PYPI == 'true' }}
-        name: Publish package to PyPI
-        uses: pypa/gh-action-pypi-publish@release/v1
-        with:
-          user: ${{ env.PYPI_USERNAME }}
-          password: ${{ env.PYPI_PASSWORD }}
-          packages_dir: ${{github.workspace}}/sdk/python/bin/dist
-
-      - if: ${{ matrix.language == 'nodejs' && env.PUBLISH_NPM == 'true' }}
-        uses: JS-DevTools/npm-publish@v1
-        with:
-          access: "public"
-          token: ${{ env.NPM_TOKEN }}
-          package: ${{github.workspace}}/sdk/nodejs/bin/package.json
-
-      - if: ${{ matrix.language == 'dotnet' && env.PUBLISH_NUGET == 'true' }}
-        name: publish nuget package
-        run: |
-          dotnet nuget push ${{github.workspace}}/sdk/dotnet/bin/Debug/*.nupkg -s ${{ env.NUGET_FEED_URL }} -k ${{ env.NUGET_PUBLISH_KEY }}
-          echo "done publishing packages"
-
-    strategy:
-      fail-fast: true
-      matrix:
-        dotnetversion:
-          - 6.0.x
-        goversion:
-          {%endraw%}- {{ cookiecutter.__go_version_major }}.{{ cookiecutter.__go_version_minor }}.x{%raw%}
-        nodeversion:
-          - 16.x
-        pythonversion:
-          - "3.9"
-        # javaversion:
-        # - "11"
-        language:
-          - nodejs
-          - python
-          - dotnet
-          - go
-          # - java
-{%endraw%}
+    - name: Check worktree clean
+      run: |
+        git update-index -q --refresh
+        if ! git diff-files --quiet; then
+            >&2 echo "error: working tree is not clean, aborting!"
+            git status
+            git diff
+            exit 1
+        fi{% endraw %}
